# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-movieactorranking-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://tonylukeregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f23689bd09d3435391813a78e892ec99 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_739cc700fbfb43c8aef472eb44c5e7a3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: tonylukeregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f23689bd09d3435391813a78e892ec99 }}/movie-actor-ranking/app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-movieactorranking-prod'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a56ba1b88fc94bf4a71f2dbeec70c2d2 }}
        images: 'tonylukeregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f23689bd09d3435391813a78e892ec99 }}/movie-actor-ranking/app:${{ github.sha }}'